---
- name: Install Mysql package
  yum: name={{ item }} state=present
  with_items:
   - mariadb-server
   - mariadb
   - MySQL-python

- name: Create Mysql configuration file
  template: src=my.cnf.j2 dest=/etc/my.cnf
  notify:
  - restart mariadb

- name: Start Mysql Service
  service: name=mariadb state=started enabled=yes
